import type { NextRequest } from "next/server";
import type Stripe from "stripe";
import { createClient } from "@supabase/supabase-js";
import { getStripe } from "@/lib/stripe/config";

/**
 * app/api/auth/exchange/route.ts
 * Token exchange endpoint for the payment-first onboarding flow.
 *
 * Called by the success page client component after guest checkout to poll
 * for the one-time login token generated by the checkout.session.completed
 * webhook. When the token is ready, the client calls verifyOtp() to establish
 * a Supabase session without the user touching their inbox.
 *
 * ─── SECURITY MODEL ──────────────────────────────────────────────────────────
 * The session_id (Stripe checkout session) is validated with the Stripe API on
 * every request. An attacker would need a valid session_id for a session they
 * paid for — at which point they're looking up their own token anyway.
 *
 * The token itself is one-time-use: verifyOtp() consumes it on the Supabase
 * side, and we clear it from the member row in this handler so it cannot be
 * read a second time.
 *
 * ─── RESPONSES ───────────────────────────────────────────────────────────────
 * { status: "pending" }                    — Webhook hasn't stored token yet.
 * { status: "ready", token_hash: string }  — Token ready; client can verifyOtp.
 * { error: string }  + 4xx                 — Bad request or invalid session.
 *
 * This endpoint has no auth requirement — the caller is the browser immediately
 * after Stripe redirects, before a session exists.
 */

// All routes are dynamic by default in Next.js 16 with cacheComponents enabled.
// The 'force-dynamic' export is no longer needed (and is now incompatible).

function getAdminClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!,
    { auth: { persistSession: false } }
  );
}

export async function GET(request: NextRequest) {
  const sessionId = request.nextUrl.searchParams.get("session_id");

  if (!sessionId) {
    return Response.json(
      { error: "Missing session_id query parameter." },
      { status: 400 }
    );
  }

  // ── Step 1: Validate session_id with Stripe ──────────────────────────────
  const stripe = getStripe();
  let checkoutSession: Stripe.Checkout.Session;

  try {
    checkoutSession = await stripe.checkout.sessions.retrieve(sessionId);
  } catch (err) {
    const message = err instanceof Error ? err.message : "Unknown error";
    console.error(`[Exchange] Invalid session_id: ${sessionId} — ${message}`);
    return Response.json(
      { error: "Invalid or expired checkout session." },
      { status: 400 }
    );
  }

  // ── Step 2: Extract email from checkout session ──────────────────────────
  const email = checkoutSession.customer_details?.email;
  if (!email) {
    console.error(
      `[Exchange] No email in session: ${sessionId}. ` +
        `Session status: ${checkoutSession.status}`
    );
    return Response.json(
      { error: "No email associated with this checkout session." },
      { status: 400 }
    );
  }

  // ── Step 3: Look up member by email ─────────────────────────────────────
  const supabase = getAdminClient();

  const { data: member, error: memberError } = await supabase
    .from("member")
    .select("onboarding_token")
    .eq("email", email)
    .single();

  if (memberError && memberError.code !== "PGRST116") {
    // PGRST116 = "no rows returned" — expected while webhook is processing
    console.error(
      `[Exchange] DB error looking up member for ${email}: ${memberError.message}`
    );
    return Response.json({ error: "Internal error." }, { status: 500 });
  }

  // ── Step 4: If token not ready, tell client to keep polling ─────────────
  // Include email so the fallback magic-link sender has it without a second Stripe call.
  if (!member?.onboarding_token) {
    return Response.json({ status: "pending", email });
  }

  // ── Step 5: Return token and immediately clear it ────────────────────────
  // The token is one-time use on Supabase's side (verifyOtp consumes it),
  // but we also null it here so a second read of this endpoint can't return it.
  const tokenHash = member.onboarding_token;

  const { error: clearError } = await supabase
    .from("member")
    .update({ onboarding_token: null })
    .eq("email", email);

  if (clearError) {
    // Non-fatal — return the token anyway so the user gets in.
    // The worst case: a second poll returns { status: "pending" } on next call.
    console.error(
      `[Exchange] Failed to clear onboarding_token for ${email}: ${clearError.message}`
    );
  }

  console.log(`[Exchange] Token exchanged for ${email} — session: ${sessionId}`);

  return Response.json({ status: "ready", token_hash: tokenHash, email });
}
