-- =============================================================================
-- 0005_add_onboarding_columns.sql
-- Positives Platform — Payment-First Onboarding Support
-- =============================================================================
-- Adds two columns to the member table to support the guest-checkout flow:
--
--   onboarding_token  — Short-lived magic-link token hash generated by the
--                       checkout.session.completed webhook immediately after
--                       account creation. The success page polls for this,
--                       exchanges it for a Supabase session (verifyOtp), then
--                       clears it. One-time use. NULL once consumed or expired.
--
--   password_set      — Set to TRUE when the member explicitly sets a password
--                       via /account settings. Used to show/hide the "secure
--                       your account" nudge banner. Never blocks product access.
--
-- Safety: Both columns use IF NOT EXISTS-safe ALTER patterns. Running this
-- migration more than once is safe — Postgres will error on duplicate column
-- names, so we guard with a DO block check.
-- =============================================================================

DO $$
BEGIN
  -- Add onboarding_token if it doesn't already exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = 'member'
      AND column_name  = 'onboarding_token'
  ) THEN
    ALTER TABLE member ADD COLUMN onboarding_token TEXT;
    COMMENT ON COLUMN member.onboarding_token IS
      'One-time magic-link token hash. Generated by checkout webhook, consumed by success page. NULL after use.';
  END IF;

  -- Add password_set if it doesn't already exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = 'member'
      AND column_name  = 'password_set'
  ) THEN
    ALTER TABLE member ADD COLUMN password_set BOOLEAN NOT NULL DEFAULT FALSE;
    COMMENT ON COLUMN member.password_set IS
      'TRUE once the member has set an explicit password via /account. Never a gate — only drives the nudge banner.';
  END IF;
END $$;
