DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = 'member'
      AND column_name  = 'onboarding_token'
  ) THEN
    ALTER TABLE member ADD COLUMN onboarding_token TEXT;
    COMMENT ON COLUMN member.onboarding_token IS
      'One-time magic-link token hash. Generated by checkout webhook, consumed by success page. NULL after use.';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = 'member'
      AND column_name  = 'password_set'
  ) THEN
    ALTER TABLE member ADD COLUMN password_set BOOLEAN NOT NULL DEFAULT FALSE;
    COMMENT ON COLUMN member.password_set IS
      'TRUE once the member has set an explicit password via /account. Never a gate — only drives the nudge banner.';
  END IF;
END $$;;
